# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e68d344b29833cf437398d9c11fe80dd27f963156d97ee16eec8230439a9de25e748205a8004b136f8a67b4cb4044a4aafc589f51732b565efd381f650e2846

test:
  secret_key_base: d42bd0cdb7ffe4ad38839fc0e1cec596a756b7d9277c76da0da5b0dc281e7b11652623d39a46f619ce6f20eda0437d6f1cb02cc3afc54dc69f6f695b1c41c376

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
